### ISSUE TITLE
Layout rendering Error in Android Studio Dolphin | 2021.3.1 Patch 1

### ISSUE THREAD

**Issue by SaezChristopher** [tfcporciuncula/phonemoji#13]
I dont understand how to fix it and it breaks the layout of the view

```java.lang.IllegalStateException: PhonemojiTextInputLayout requires a PhonemojiTextInputEditText child
	at com.fredporciuncula.phonemoji.PhonemojiTextInputLayout.watchPhoneNumber(PhonemojiTextInputLayout.kt:51)
	at com.fredporciuncula.phonemoji.PhonemojiTextInputLayout.onAttachedToWindow(PhonemojiTextInputLayout.kt:46)
	at android.view.View.dispatchAttachedToWindow(View.java:20753)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:58)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:366)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by tfcporciuncula** [comment]
There's not enough information for me to understand and investigate the problem. I'll close the issue for now, but feel free to reopen it with a minimum reproducible example or at least more details and a complete stacktrace.
