### ISSUE TITLE
Problems with Layout preview in Android Studio

### ISSUE THREAD

**Issue by hotellinawebmaster** [tfcporciuncula/phonemoji#17]
Environment: Android Studio Flamingo | 2022.2.1 Patch 1

Hello, I am using your amazing library, but I get this error when working with the layout preview in Android Studio. Is there anything we can do for it?
The library works okay at runtime 😍.

![image](https://github.com/tfcporciuncula/phonemoji/assets/73776127/68de729e-2aeb-41f6-81fd-b43cd4f3bcf6)

java.lang.IllegalStateException: PhoneNumberUtil instance hasn't been initialized.
	at com.fredporciuncula.phonemoji.internal.PhoneNumberUtilInstanceProvider.get(PhoneNumberUtilInstanceProvider.kt:13)
	at com.fredporciuncula.phonemoji.PhonemojiTextInputEditText.<init>(PhonemojiTextInputEditText.kt:22)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:426)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:437)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:341)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:353)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:450)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:122)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:727)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:884)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:195)
	at com.android.tools.idea.rendering.RenderExecutor$PriorityRunnable.run(RenderExecutor.kt:293)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tfcporciuncula** [comment]
Thanks for reporting this, I actually never gave any thoughts on making it work on previews! The library currently depends on the [App Startup](https://developer.android.com/topic/libraries/app-startup) lib to initialize [`PhoneNumberUtil`](https://github.com/google/libphonenumber), which of course doesn't happen on previews — and can't happen as the phone service isn't available, which is something `PhoneNumberUtil` depends on.

So even though we won't be able to make the component work on preview (showing the country flag and formatting input), we can at least avoid breaking it and then perhaps we can make it look decent with some `tools:text`.

I've just fixed this [here](https://github.com/tfcporciuncula/phonemoji/commit/592a3366a80325154425364073acced4d7b77e6f) and updated the sample preview, new release will be coming soon!

**Comment by hotellinawebmaster** [comment]
Thanks a lot, I tested the preview with the new changes and it works.
