### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: View referenced in flagFor isn't a PhonemojiTextInputEditText

### ISSUE THREAD

**Issue by afsar-ali** [tfcporciuncula/phonemoji#18]
This is crash I'm getting for many devices.

Fatal Exception: java.lang.IllegalStateException: View referenced in flagFor isn't a PhonemojiTextInputEditText
       at com.fredporciuncula.phonemoji.PhonemojiFlagTextView.watchPhoneNumber(PhonemojiFlagTextView.kt:47)
       at com.fredporciuncula.phonemoji.PhonemojiFlagTextView.onAttachedToWindow(PhonemojiFlagTextView.kt:42)
       at android.view.View.dispatchAttachedToWindow(View.java:20874)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5293)
       at android.view.ViewGroup.addView(ViewGroup.java:5076)
       at android.view.ViewGroup.addView(ViewGroup.java:5016)
       at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:833)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2180)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
       at android.os.Handler.handleCallback(Handler.java:978)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8089)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

XML Code :

<LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:padding="@dimen/dp_12">

                <com.fredporciuncula.phonemoji.PhonemojiFlagTextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/margin_medium"
                    android:gravity="center"
                    android:textSize="@dimen/sp_18"
                    app:phonemoji_flagFor="@id/etPhoneNumber" />

                <com.fredporciuncula.phonemoji.PhonemojiTextInputEditText
                    android:id="@+id/etPhoneNumber"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/margin_medium"
                    android:background="@null"
                    android:fontFamily="@font/lato_bold"
                    android:hint="@string/enter_mobile_hint"
                    android:imeOptions="actionDone"
                    android:textColor="@color/text_black"
                    android:textColorHint="@color/stroke_color"
                    android:textSize="@dimen/sp_18" />

            </LinearLayout>

**Comment by tfcporciuncula** [comment]
Are you able to reproduce it with that code or are you just receiving crash reports? It would be helpful to have a reproducible example.
